### ISSUE TITLE
Grafici sbagliati con certe reti

### ISSUE THREAD

**Issue by dallagi** [e-dorigatti/py_digitrec#1]
Ho notato che certi grafici, specialmente per reti di grandi dimensioni, mostrano precisione quasi costante e molto bassa. Penso sia un problema della rete neurale

**Comment by e-dorigatti** [comment]
I grafici sono carini però :P

**Comment by e-dorigatti** [comment]
È vero, probabilmente è legato al calcolo del gradiente. Forse con molti neuroni il gradiente è numericamente talmente vicino a zero che si presentano degli errori considerevoli

**Comment by e-dorigatti** [comment]
Ma LOL 2014! E grafici carini hahah XD

Comunque confermo che sono problemi di gradiente e anche problemi di ottimizzazione. Usare ReLU [1] invece che sigmoid come attivazione e un ottimizzatore avanzato [2] sicuramente aiuterebbe.

Grazie per l'issue, avrei potuto ricevere un PhD anticipato se solo ci avessi lavorato con zelo ;)

[1] Maas, A. L., Hannun, A. Y. & Ng, A. Y. Rectifier nonlinearities improve neural network acoustic models. in in ICML Workshop on Deep Learning for Audio, Speech and Language Processing (2013).
[2] Kingma, D.P. and Ba, J. (2015) Adam: a Method for Stochastic Optimization. The 3rd International Conference for Learning Representations, San Diego.

**Comment by dallagi** [comment]
Ahahaha perdonami, stavo facendo pulizia tra le issues aperte su github e ho pensato avesse senso chiudere questa dopo 8 anni :joy:
